# Generated by Django 4.1 on 2024-02-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassigned',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
