# Generated by Django 4.1 on 2024-02-18 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_taskassigned_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassigned',
            old_name='isActive',
            new_name='isOwner',
        ),
        migrations.AlterField(
            model_name='log',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.task'),
        ),
    ]
