# Generated by Django 4.1 on 2024-02-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_isactive_taskassigned_isowner_alter_log_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassigned',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
    ]
